/* No keys in this file. Values come from .env (via env.js, generated by: node build-env.js). */
(function () {
  var e = window.ENV || {};
  window.FIREBASE_CONFIG = {
    apiKey: e.FIREBASE_API_KEY,
    authDomain: e.FIREBASE_AUTH_DOMAIN,
    projectId: e.FIREBASE_PROJECT_ID,
    storageBucket: e.FIREBASE_STORAGE_BUCKET,
    messagingSenderId: e.FIREBASE_MESSAGING_SENDER_ID,
    appId: e.FIREBASE_APP_ID,
    measurementId: e.FIREBASE_MEASUREMENT_ID
  };
})();
